cutechess/cutechess

projects/lib/src/board/berolinaboard.cpp
projects/lib/src/board/berolinaboard.h
projects/lib/src/board/board.cpp
projects/lib/src/board/board.pri
projects/lib/src/board/boardfactory.cpp
projects/lib/src/board/westernboard.cpp
projects/lib/src/board/westernboard.h
projects/lib/tests/chessboard/tst_board.cpp

removed a duplicate test case and squashed the commits

begin support for Berolina

---

projects/gui/src/mainwindow.cpp

It is more convenient to play with an automatically flipped board. #148

Automatically flip the board if human plays the black side against an engine

---

docs/cutechess-cli.6
projects/cli/res/doc/help.txt

Update of cutechess-cli documentation: recently added chess variants. #192

add new variants to documentation

---

projects/lib/src/board/ncheckboard.cpp

Only changes in comments:
Give credit to the scidb project for the Three-check Chess FEN check counter extension.

updated comments for n-check chess

---

projects/lib/src/xboardengine.cpp

This is a proposal to support the alternative move format especially used by older xboard (CECP) engines.
Software collections often contain some or many older engines that do not work with cutechess.
Some variants have significant share of old engines.
While the prevalent move format for xboard engines is
`move e2e4` 
using algebraic notation  (or even using SAN `move e4`), the alternative format
`1. ... e2e4`
is still part of the specification, even for V2 engines.
This patch supports the alternative format 
NUMBER ... MOVE 	
in addition to the the prevalent format
move MOVE .
It has been tested with various engines and resolves problems with
_gnuchessx 6.1.1_
_phalanx XXII-pg_
which use the alternative format.
xboard communication format CECP is defined in: …

support CECP V1 moves (xboard/gnuchessx old style moves)

---

projects/lib/src/board/board.cpp
projects/lib/src/board/ncheckboard.cpp
projects/lib/src/xboardengine.cpp

This patches some of the weaknesses found by clazy, issue #236 .

work on issue #236

---

projects/lib/tests/chessboard/tst_board.cpp

updated comments and added some perft values
Additional test for `twokings` as promised in comments about c31ff03.
HTH

added castling tests for Two Kings Each Chess (Wild/9),

---

projects/lib/src/board/janusboard.cpp

fix inaccuracy in JanusBoard::moveFromSanString

---

projects/gui/3rdparty/modeltest/modeltest.cpp

This fixes #317 and is the minimum fix as discussed there (same change as in http://code.qt.io/cgit/qt/qtbase.git/tree/tests/auto/other/modeltest ),

Fix linking problem of modelTest in debug config

---

projects/lib/src/chessgame.cpp
projects/lib/src/pgngame.cpp
projects/lib/src/pgngame.h

This PR supports #332. I am not sure everybody likes the tags, so it might be better to make the tags optional.

PGN timestamp tags

---

projects/lib/src/board/shatranjboard.cpp
projects/lib/src/board/shatranjboard.h

This patch is intended to fix #339.

ShatranjBoard now based on WesternBoard instead of StandardBoard

---

projects/gui/src/gamedatabasedlg.cpp
projects/gui/src/main.cpp
projects/gui/ui/timecontroldlg.ui
projects/lib/src/board/shatranjboard.cpp

This PR makes GUI load translations by auto-detecting system locale.
It would be better to do this step by step. Previous PR will be closed.

Enable translation by auto-detecting system locale.

---

docs/cutechess-cli.6
projects/cli/res/doc/help.txt
projects/cli/src/main.cpp
projects/gui/src/main.cpp
projects/lib/src/board/seirawanboard.h
translations/cutechess_zh_CN.ts

Small changes in data, comments and documentation.

Small fixes, update copyright and documentation dates

---

.appveyor.yml
projects/lib/src/chessengine.cpp

Especially with 20 block network cutechess is unreliable to start up leela lc0 without timing out. It takes about 9s on my computer if nothing else is running.

Leela times out on startup often

---

projects/lib/src/board/seirawanboard.cpp
projects/lib/src/board/shatranjboard.cpp
projects/lib/src/board/sittuyinboard.cpp
projects/lib/src/board/westernboard.cpp

These are from the lib/src/board subdirectory.
For the Chess::Board classes I verified that all the  `Maybe you meant to call ...`  warnings can be ignored.

Fix some clazy reported problems

---

projects/gui/src/engineselectiondlg.cpp
projects/gui/src/engineselectiondlg.h
projects/gui/src/newtournamentdialog.cpp
projects/gui/src/newtournamentdialog.h

Add engines to tournament by double-click

---

docs/cutechess-cli.6
projects/cli/res/doc/help.txt
projects/gui/ui/gamesettingswidget.ui

Adding a sentence to clarify the properties of the draw adjudication per draw move count.
Resolves #429

Help texts for draw adjudication: irreversible moves reset the counters.

---

projects/lib/src/board/board.h
projects/lib/src/board/chancellorboard.h
projects/lib/src/board/hoppelpoppelboard.h
projects/lib/src/board/modernboard.h
projects/lib/src/board/placementboard.h
projects/lib/src/board/rifleboard.cpp
projects/lib/src/board/rifleboard.h
projects/lib/src/board/sittuyinboard.cpp

This PR includes no functional changes.

Minor corrections in comments

---

projects/gui/src/mainwindow.cpp

Update tags shown for finished tournament games

---

.travis.yml

Add qt511 to travis

---

projects/gui/src/evalhistory.cpp
projects/gui/src/evalhistory.h
projects/gui/src/mainwindow.cpp
projects/lib/src/pgngame.cpp
projects/lib/src/pgngame.h

Uses PGN comments to reconstruct the evaluation history.
Resolves #233

Evaluation history for finished tournament games.

---

projects/gui/src/boardview/boardscene.cpp
projects/gui/src/mainwindow.cpp
projects/lib/src/board/gryphonboard.cpp
projects/lib/src/board/hoppelpoppelboard.cpp
projects/lib/src/board/knightmateboard.cpp
projects/lib/src/board/makrukboard.cpp
projects/lib/src/board/placementboard.cpp
projects/lib/src/board/rifleboard.cpp
projects/lib/src/board/sittuyinboard.cpp
projects/lib/src/board/twokingseachboard.cpp
projects/lib/src/board/westernboard.cpp
projects/lib/src/chessengine.cpp

Avoid returning void expressions (get rid of some potential clazy warnings)

---

projects/gui/src/boardview/boardscene.cpp
projects/gui/src/boardview/graphicsboard.cpp
projects/gui/src/boardview/graphicsboard.h

This patch draws wall squares in a dedicated color.
It aims to improve the scene for Gustav III's chess. Resolves #467.

Draw Wall squares

---

projects/lib/src/chessengine.h
projects/lib/src/xboardengine.cpp
projects/lib/src/xboardengine.h
projects/lib/tests/tests.pri
projects/lib/tests/tests.pro
projects/lib/tests/xboardengine/tst_xboardengine.cpp
projects/lib/tests/xboardengine/xboardengine.pro

Adds units tests to the XboardEngine class.

Unit tests

---

projects/lib/src/xboardengine.cpp

Fix: Write to XboardEngine's evaluation field

---

projects/gui/src/boardview/boardscene.cpp

Draw nicer move arrow, similar to lichess.org arrows. Second patch has images for preview, not intended for merge.

Nice arrow
