projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/kingofthehillboard.cpp, projects/lib/src/board/kingofthehillboard.h, projects/lib/tests/chessboard/tst_board.cpp
This adds support for the variant kingofthehill ("King of the Hill")  to the library. It uses `StandardBoard` as base. So it is only necessary to apply the one extra rule and test for a win for a king on a center field.
It has been tested manually and using Sjaak II version 1.3.1a and a recent version of the Stockfish multi-variant fork of D. Dugovic and team https://github.com/ddugovic/Stockfish.git .
=> begin support for variant King of the Hill

projects/lib/src/chessplayer.cpp, projects/lib/src/timecontrol.cpp, projects/lib/src/timecontrol.h
Some users prefer to not increase available time if book moves are applied. Currently, any move causes a pre-defined time increment.  #9 
This simple patch does not have configurable settings.
=> do not use time increment for book moves

projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/racingkingsboard.cpp, projects/lib/src/board/racingkingsboard.h, projects/lib/tests/chessboard/tst_board.cpp
This adds support for the variant racingkings ("Racing Kings") to the library.  Racing Kings Chess is a race game and a checkless chess variant.
This software has been tested with a recent version of the multi-variant fork of the Stockfish engine  https://github.com/ddugovic/Stockfish.git. It also works with lichess.org PGN game files (after patching the variant name "Racing Kings" to "racingkings", but this is a topic already listed in the issues list).
=> begin support for Racing Kings variant

projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/hordeboard.cpp, projects/lib/src/board/hordeboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support the Horde Chess variant(s). Horde chess is a variant that is similar to Dunsany's chess of 1942. A standard chess set of pieces faces a horde of pawns. The pieces must eliminate all pawns to win. The pawns go to checkmate the opponent king. Standard rules apply,
This patch implements the modern variant with 36 white pawns (lichess.org, stockfish). It is quite general and can also be used with switched black/white setup (like older Horde variant). 
The version was tested using stockfish variant fork https://github.com/ddugovic/Stockfish.
I had to adapt the en passant rules to not accept e.p. on rank 2 but to allow double steps from rank 1 (matching perft of stockfish).
A change to WesternBoard makes the assertion of number of kings more flexible (the horde has …
=> support Horde Chess

projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/ncheckboard.cpp, projects/lib/src/board/ncheckboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/tests/chessboard/tst_board.cpp
This patch adds support for Three-Check (actually N-Check) Chess.
Giving Check n times is an additional way to win a chess game.
Variant `3check` was tested manually and also using PyChess, Sjaak II and the Stockfish fork (https://github.com/ddugovic/Stockfish). For my tests I patched stockfish for that variant string, it normally uses `threecheck`).
This version can read various FEN formats, including standard chess FEN and extended FENs from lichess.org with check counters appended to the FEN (like <fen> +0+0) as well as a format suggested by H. G. Muller and implemented into Stockfish. The latter uses backward counters like <fen up to e. p. field> 3+3 <rest of fen string> and only one plus sign.  The writing format yet has to be determined. Currently reverse counters are appended to …
=> support for Three-Check Chess

projects/lib/src/board/westernboard.cpp, projects/lib/tests/chessboard/tst_board.cpp
This patch adds a FEN extension for variants with ambiguous en-passant cases.
The en-passant field comprises of ep square (destination square of capture move) and ep target (square of capture victim) like `d6e5`. 
This format was introduced by H. G. Muller and implemented into xboard (development version > 4.9.1).
=> Berolina FEN ep extension

projects/gui/src/mainwindow.cpp
At the end of a tournament tab message box and results window have a tendency to get into each other's way.
So I suggest to only protect a tourney game tab if the corresponding game is active. I made some malicious tests already (for running games, close while waiting between games, before and after tournament finished, also with different delays of confirmation). #157
=> only protect a tournament game tab if the corresponding game is active

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/chessgiboard.cpp, projects/lib/src/board/chessgiboard.h, projects/lib/src/board/crazyhouseboard.cpp, projects/lib/src/board/crazyhouseboard.h, projects/lib/src/board/loopboard.cpp, projects/lib/src/board/loopboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support the _Loop Chess_ and _Chessgi_ variants. Loop Chess is a variant that is similar to _Crazyhouse_. Captured pieces change sides and can be dropped onto empty squares later. In contrast to Crazyhouse, promoted pawns keep their piece rank when captured in Loop Chess. 
The implementation uses `CrazyhouseBoard`, which is modified to allow overriding promoted piece types. I tested with recent Stockfish multivariant versions and with TJchess 1.3.
Chessgi differs from Loop Chess only in drop rule for pawns: Chessgi allows to drop pawns on a side's own first rank.
The implementation of `ChessgiBoard` relies on `LoopBoard`. Tests were done with Sjaak II versions 1.3.1a and 1.4.1. Currently cutechess allows double steps from first rank and second rank, Sjaak II only …
=> support Loop Chess and Chessgi

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/extinctionboard.cpp, projects/lib/src/board/extinctionboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support the _Extinction Chess_ and _Kinglet Chess_ variants.
In _Extinction Chess_ a side wins if their opponent loses all pieces of any kind. The King is a normal piece, there is no check and Pawns can also promote to King.
_Kinglet Chess_ is an older variant: A side wins if their opponent lost all Pawns. Pawns can promote to King only. 
I only tested manually. The engines I have either do not play these variants or are very old and require some more work on the interfaces. Nevertheless I hope this is useful.
=> support Extinction Chess and Kinglet Chess

projects/lib/src/board/board.cpp, projects/lib/src/board/board.h, projects/lib/src/board/crazyhouseboard.cpp, projects/lib/src/board/crazyhouseboard.h, projects/lib/src/board/loopboard.cpp, projects/lib/src/board/loopboard.h, projects/lib/tests/chessboard/tst_board.cpp
This patch extends the FEN parser in `Board::setFenString`. It supports multi-character piece symbols up to a length `maxsymlen` which depends on the predefined piece types. The longest match prevails, e.g.  the variant `Crazyhouse` uses `maxsymlen = 2` and so `Q~` (Pawn promoted to Queen) can be set instead of `Q` (Queen). This resolves issue #198.
Currently, apart from `Crazyhouse` and subvariants `maxsymlen`  equals one. Thus the reader will not be significantly slower.
Note: This extension only refers to pieces on the board, not to pieces in the reserve (in hand).
I hope this is useful. 
(updated patch and comment)
=> enable FEN parser to work with multi-character piece symbols

projects/lib/src/board/board.cpp, projects/lib/src/board/board.h, projects/lib/src/xboardengine.cpp
This is a proposal to support board setup for xboard engines that do not have the `setboard` feature. Instead of `setboard` the `edit` command is used to place the pieces.
The `edit` command is part of the CECP specification.
> The edit command is the old way to set up positions. For compatibility with old engines, it is still used by default, but new engines may prefer to use the feature command (see below) to cause xboard to use setboard instead.
http://www.open-aurec.com/wbforum/WinBoard/engine-intf.html
https://www.gnu.org/software/xboard/engine-intf.html
_Chessbase/Fritz_ extensions for en passant and castling `ep` and `castle` (see remarks at the end of CECP specification) are not supported yet.
I hope this is useful nevertheless.
=> use edit command for xboard engines without setboard feature

projects/lib/src/chessgame.cpp
The xboard (CECP) specification now maps (absolute) mate scores just above 100000 with mate distance in moves instead of plys.
> Mate scores should be indicated as 100000 + N for "mate in N moves", and -100000 - N for "mated in N moves".
https://www.gnu.org/software/xboard/engine-intf.html
I found that Fairy-Max 5.0b implements this new specification.
This patch adds support for the new mate scores. So it shows  +M9 instead of 1000.05 and -M10 instead of -1000.05. The scores out of (absolute) range 99900 to 100100 are unchanged. So far I have not seen any new problems with older mate score formats.
=> Support new mate score format of xboard engines in addition to old one

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/checklessboard.cpp, projects/lib/src/board/checklessboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support _checkless chess_. This is an old variant of standard chess. No checks are allowed except for giving mate. Tested by manual play, as there seems to be a lack of available chess engines. This is a lightweight implementation. 
Test position `K5kr/5Q2/8/8/8/8/8/8 b - - 0 1`  is correctly solved as a white win.
=> support Checkless Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/gui/src/boardview/boardscene.cpp, projects/lib/src/board/board.cpp, projects/lib/src/board/board.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/janusboard.cpp, projects/lib/src/board/janusboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support _Janus Chess_. This variant uses a 10x8 board and introduces the _Janus_, a piece with Knight and Bishop movement. This piece is  also known as _Princess, Archbishop, Hawk_ etc. in the context of other variants. As this piece is able to give mate on its own, the draw rate tends to be lower than in standard chess. It is similar to Capablanca Chess, but has different castling rules, different board setup, and one more Bishop+Knight piece per side instead of the _Chancellor_ (Rook+Knight).
Tests were done manually and with the engine Fairy-Max 5.0b .
I tried to abstract the notation symbol of the Janus "J" from the representation symbol on the graphical board scene. `JanusBoard` uses the "A" (Archbishop) graphical representation. In order to achieve this I made …
=> support Janus Chess

projects/lib/src/board/hordeboard.cpp
This corrects the PGN comments for wins of the pieces in Horde Chess. Comment currently is  `{1 wins}`  if the horde starts for the white side. Sorry for the glitch.
=> Horde: correct result string for black win

projects/lib/src/xboardengine.cpp
This patch resolves problems setting up positions with black side to move and xboard - engines.
I observed that engines started playing the white side when a black position was given.
A command sequence is used according to the CECP specification https://www.gnu.org/software/xboard/engine-intf.html as described for the edit command. It includes a dummy move to switch the engine from the white to the black side.
Now force mode is set earlier, this also resolves problems I observed with sjaakii (e.g. version 1.4.1).
=> Cecp position set-up with black to move

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/andernachboard.cpp, projects/lib/src/board/andernachboard.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support **Andernach Chess**. Except for the kings a piece switches sides after it made a capture. A pawn capturing on the eighth rank first promotes and then switches sides. Apart from this standard chess rules apply. This variant originated from problem chess but can also be played in competition. A computer implementation has advantages against over the board play. The latter needs two sets of chess pieces and more interaction to exchange capturing pieces.
There seem to be no engines for this variant yet. Other than by playing myself in order to test the implementation I made some crude changes to the _sloppy_ engine.
While there I implemented boards for **Anti-Andernach Chess** (switch sides after non-captures) and  **Super-Andernach Chess** (always sitch sides …
=> support Andernach chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/knightmateboard.cpp, projects/lib/src/board/knightmateboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a patch to support **Knightmate**. Here kings move like standard knights and vice versa. Castling moves are unchanged /wrt standard chess. 
I tested this implementation with some versions of _Fairy Max_ and _Sjaak II_. On the board the `King` is represented graphically by a `Knight` piece and the standard Knights are replaced by `Mann` or `Commoner` pieces that look like standard Kings.
=> support KnightMate

projects/lib/src/board/westernboard.cpp
This patch extends SAN move disambiguation to kings. This resolves errors in variants with possibly more than one king per side, e.g. _Antichess_ and _Suicide Chess_ , among others.
With two kings of the same colour on e4 and g4, a move to f4 will then have a notation `Kef4` or `Kgf4` (instead of `Kf4`).
=> SAN disambiguation for kings

projects/lib/src/board/westernboard.cpp
In variant play with multiple kings per side a king may be exposed to threats by any opponent king. This is relevant for multi-king-variants like _Two Kings Each Chess (Wild 9)_,  _Gryphon  Chess_, and others.
This patch makes `WesternBoard::inCheck()` more flexible. As far as I know this has no relevant functional (and speed) impact on the processing of main chess variants.
=> support inCheck for multiple Kings on the opponent side

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/gridboard.cpp, projects/lib/src/board/gridboard.h, projects/lib/src/board/restrictedmoveboard.cpp, projects/lib/src/board/restrictedmoveboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support Grid Chess, a chess variant with an additional move restriction.
The board is devided into regions of 2x2 square. Moves within the regions are forbidden. So a piece cannot be captured or protected from inside its region. A king can not be checked from inside its region.
The implementation of `GridBoard` uses `RestrictedMoveBoard` as base class. This class can also be re-used for other variants.
_Grid Chess_ is accompanied by some related variants, where either the grid is displaced by file and rank or berolina pawns are used which more easily move between the grid's regions.
GridChessBoard has been tested manually and by engine-engine play with a hacked-up version of _Sloppy_.
The other variants have been tested manually.
=> support Grid Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/antiboard.cpp, projects/lib/src/board/antiboard.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/giveawayboard.cpp, projects/lib/src/board/giveawayboard.h, projects/lib/src/board/suicideboard.cpp, projects/lib/src/board/suicideboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/uciengine.cpp, projects/lib/src/uciengine.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support  _Losing Chess_  variants _Antichess_, _Giveaway_, _Suicide_. (Currently there are some problems.)
In _Losing Chess_ a side that lost all pieces or cannot move wins. The King is a normal piece, there is no check and Pawns can also promote to King. If a side can capture a piece, the must do so.
The variant labelled _Antichess_ is the oldest and has no castling moves. _Giveaway_ is identical, but castling is allowed. _Suicide Chess_ is like _Antichess_ but in stalemate the side with less pieces wins.
`GiveawayBoard` and `SuicideBoard` were implemented as subclasses of `AntiBoard`.
I tested _Giveaway_ and _Suicide Chess_ with recent multivariant Stockfish and Sjeng 11,2. The latter was also tested using Sjaak II 1.3.1a and PyChess. _Antichess_ was test manually …
=> support Losing Chess (Antichess, Giveaway, Suicide)

projects/lib/src/chessgame.cpp, projects/lib/src/uciengine.cpp, projects/lib/src/xboardengine.cpp, projects/lib/src/xboardengine.h
Very high non-mate scores of UCI engines collide with the xboard mate score detection. Most engines are using lower scores, but e.g. _Houdini 5_ issues very high scores. For example, a UCI score of 99.99 gets translated to +M1, a false positive mate score. Reference: #250 
This patch moves most of the mate score preparation for xboard-scores from `ChessGame` into `XboardEngine`. The virtual mate scores now are mapped into the range around 98000 cp. `UciEngine` was adapted accordingly.
Remarks:
- While there I made a correction to the code for new Xboard scores.
- The choice 99000 for the virtual mate score was deliberate. It could be lower or higher. I also tried to use 200000 but then the output does not quite fit into the "Score" field on screen, but one could of course widen it.
- The …
=> Separate UCI and Xboard high and mate scores

projects/gui/res/chessboard/default.svg
This is a suggestion to extend the default piece set Wiki by CBurnett further from 2 x 12 pieces to 2 x 20 pieces.
I suggest to add new pieces:
The new pieces are indexed RN, M, U, F, E, W, NR, ZE, rn, m, u, f, e, w, nr, ze for Royal Knight, Mann, Unicorn, Ferz, War Elephant (Alfil), Wazir, NightRider, and Zebra.
A preview of the full set (click to view):
The set was assembled from various authors/artists, the preexisting licenses allow to release the combined work under licenses Creative Commons CC-BY-SA/3.0 (share under same conditions and with attribution to the originators) and probably GNU General Public License V3.
The original set King, Queen, Rook, Bishop, Knight, and Pawn was released by C. Burnett to Wikipedia under various licenses, including the licenses mentioned before.
The …
=> Expansion of Wiki CBurnett Piece Set (default)

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/twokingseachboard.cpp, projects/lib/src/board/twokingseachboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support the chess variant _Two Kings Each_, also known as _wild9_, as per user request (discussion among other topics in #242). It is played on chess server ICC. 
Wild 9 is a variant with two Kings on each side. Only the King of either side that is currently closer to the a-file is royal and subject to check and mate. The other King is a normal piece and can be captured. Only the king starting on the e-file is able to castle. The castling rights are lost when any of the two kings of a side moves.
When two kings of a side are on the same file, the king closer to the first white rank is royal (i.e both sides refer to square a1), so the game has an asymmetry.
The `twokings` implementation `TwokingsEachBoard` has been tested with the existing engine pulsar2009-9b-64 …
=> Support variant Two Kings Each (Wild9)

projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/janusboard.cpp, projects/lib/src/board/knightmateboard.cpp, projects/lib/tests/chessboard/tst_board.cpp
This PR is intended for the maintainance of some recent additions
and comprises of 3 parts: 
1) I suggest to change the graphical representation of KnightMate:
King to use Royal Knight graphical symbol instead of Knight symbol.
Mann to use Mann symbol instead of King symbol.
2) fix for Janus and Knightmate: I noticed that the SAN notation with trailing symbols, e.g.  O-O-O+ or O-O-O! was not processed correctly. 
3) remove some duplicate includes in boardfactory.cpp, They had slipped into master via my anti-0 branch.
HTH
=> KnightMate using new symbols, fix for castling notation in KnightMate and Janus

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/threekingsboard.cpp, projects/lib/src/board/threekingsboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a proposal to support _Three Kings Chess_. This is a variant quite different from _Two kings Each (Wild9)_.
In this variant, both sides have three kings and all of these are normal pieces. There is no check. The side that catches one of the opponent's kings wins. The starting position has a king in the middle of the back rank, and there are no rooks but kings at the corners. So the defense has to be balanced.
This variant has been tested by manual play.
=> support Three Kings Chess

projects/gui/src/mainwindow.cpp, projects/gui/src/mainwindow.h, projects/gui/src/settingsdlg.cpp, projects/gui/ui/settingsdlg.ui
This patch adds a configuration option to `Settings/General` to close the initial tab of cutechess GUI, provided that other game tabs are open and the first tab has not been used for playing.  #114
=> close initial game tab if unused

projects/gui/src/mainwindow.cpp, projects/gui/src/newtournamentdialog.cpp, projects/gui/src/settingsdlg.cpp, projects/gui/src/settingsdlg.h, projects/gui/ui/settingsdlg.ui, projects/gui/ui/tournamentsettingswidget.ui
This patch introduces settings into the configuration of cutechess GUI that specify a default PGN file name for non-tournament games (preset games.pgn) and a default tournament PGN file name (preset tournaments.pgn). They can be found in the General and the Tournament settings tabs.
The change helps to avoid loss of game information, especially of tournament games, if a user forgets to specify a tournament output file or to save a game directly.
References: issues #147 (#208), and  #210
=> configurable default PGN files for single games and for tournament games

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/cli/src/main.cpp, projects/lib/src/tournament.cpp, projects/lib/src/tournament.h
This patch helps to save the end positions of games into a specified file.  The notation is done in EPD (more exactly: FEN) format, one line per position.
This is part of #251
=> EPD (or rather FEN) output of end position into a file (lib and cli)

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/pocketknightboard.cpp, projects/lib/src/board/pocketknightboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support _Pocket Knight Chess_, a chess variant where each side has an extra knight in his pocket (reserve) which can be dropped onto an empty square instead of a normal move. So this is a very conservative type of drop chess which might appeal to people that are not familiar with drop chess. Pocket Knight Chess has been popular in The Netherlands and in Germany already at the beginning of the 20th century.
There are sub-variants of Pocket Knight with different set-up. There are remarks /wrt this in the code.
This implementation (main variant with the simplest rules) has been tested with _Sjaak II_, versions 1.3.1a and 1.4.1.
=> support Pocket Knight Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/coregalboard.cpp, projects/lib/src/board/coregalboard.h, projects/lib/tests/chessboard/tst_board.cpp
This patch supports _Co-regal Chess_, where the Queens are subject to check and mate just as the Kings. This implementation follows the original rules by Vernon R. Parton, i. e. there is no castling of Queens. It is quite compact and based on `WesternBoard`.
=> support Co-regal Chess

projects/gui/src/mainwindow.cpp, projects/gui/src/mainwindow.h, projects/lib/src/chessgame.cpp, projects/lib/src/chessgame.h
This patch adds three menu items to the "Game" menu. The user can adjudicate an _ongoing_ game as Draw, White Win, and Black Win: a call to a new slot on the `ChessGame` class stops and adjudicates the game displayed in the current game tab (single game or tournament game).
Refer to #211 (for ongoing games)
=> Game adjuducation by user

projects/gui/src/newtournamentdialog.cpp
This patch prevents the user from starting a tournament with non-unique configuration names. If there are ambiguities in the engine list the `NewTournamentDialog::canStart()` method returns false and the start button gets disabled. Furthermore the button shows a "Resolve Duplicates!" text as long as there are duplicates in the list.
Resolution can be accomplished by removing or renaming entries of engine configurations.
Reference: Request #213
=> Do not start tournament with duplicate configuration names

projects/gui/src/engineconfigurationmodel.cpp
This patch shows duplicate entries in the list of tournament engine configurations. Non-unique entries are marked grey (the user has to resolve the duplicates by renaming or removing entries).
This is not optimised for speed. However, lists with several hundred entries are no problem on my modest laptop.
This PR refers to issue #213 and PR #271.
=> mark duplicates in engine configuration list

projects/gui/src/newtournamentdialog.cpp, projects/gui/src/settingsdlg.cpp, projects/gui/src/settingsdlg.h, projects/gui/ui/newtournamentdlg.ui, projects/gui/ui/settingsdlg.ui
This patch helps to save end positions of tournament games in FEN format, one position per line when using the GUI.
This is part of #251 and complements PR #266.
=> output of end positions of tournament games into a file (gui)

projects/gui/res/chessboard/MaurizioMonge/celtic.svg, projects/gui/res/chessboard/MaurizioMonge/eyes.svg, projects/gui/res/chessboard/MaurizioMonge/fantasy.svg, projects/gui/res/chessboard/MaurizioMonge/fantasy_alt.svg, projects/gui/res/chessboard/MaurizioMonge/freak.svg, projects/gui/res/chessboard/MaurizioMonge/prmi.svg, projects/gui/res/chessboard/MaurizioMonge/skulls.svg, projects/gui/res/chessboard/MaurizioMonge/spatial.svg, projects/gui/res/chessboard/chessboard.qrc
This PR includes eight SVG piece sets for standard chess by Maurizio Monge published [here](http://poisson.phc.unipi.it/~monge/chess_art.php). The piece sets are already in use by Wikipedia, Xboard, PyChess and others. I adapted the SVG files to use CuteChess compatible index strings and added license metadata for [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), which is GPL V3 one-way-compatible.
_Remark to users_: To use the piece set with cutechess GUI one has to wait for a GUI patch for piece selection. 
Adventurous users may try to rename `default.svg `to `default.svg.orig` and copy a new piece set to `default.svg` instead (within directory `projects/gui/res/chessboard`). Then recompile the GUI. The sets only contain the 6 standard piece types, so you will see void …
=> Eight piece sets by Maurizio Monge

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/embassyboard.cpp, projects/lib/src/board/embassyboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support Embassy Chess, a free Capablanca Chess variant by Kevin Hill, introduced in 2005. Its 10x8 starting position resembles both standard chess (8x8) and Grand Chess (10x10).
The implementation of `CapablancaBoard` castling does not match the castling rules for Embassy Chess (3 squares from e-file to b- or h-file). `EmbassyBoard` is a light-weight subclass of `CapablancaBoard`. SAN notation of castling is O-O-O for lower file castling (to b-file, king-side in chess and Embassy variant) and O-O for upper-file castling. This is consistent with xboard and with the engines I used for testing: Sjaak II (versions 1.3.1 and 1.4.1) and Fairy-Max 5.0b.
=> support Embassy Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/twokingseachboard.cpp, projects/lib/src/board/twokingseachboard.h, projects/lib/tests/chessboard/tst_board.cpp
#The id `sortland9` for the symmetrical version of _Two Kings Each Chess_ (ICC Wild/9) has been chosen ad-hoc. Recently _Two Kings Each Chess_ (`twokings`) has been added to Multi-Variant [Stockfish](https://github.com/ddugovic/stockfish/) and the symmetrical version will also be included. It was [suggested](https://github.com/ddugovic/stockfish/issues/431) to use `twokingssymmetric`, a more chess-related variant identifier. As far as I know, no third party engines are affected by this change.
This id change would help testing the symmetrical variant in multi-variant Fishtest, too.
=> Use better name on interface for Symmetrical Two Kings Each variant

projects/lib/src/tournament.cpp
This patch resolves a problem when playing repetitions using a polyglot opening book.
=> play repetitions when using polyglot book, resolves #297

projects/lib/tests/chessboard/tst_board.cpp
The board test suite does not include any tests for Atomic Chess. This PR adds 1 move string test and 3 perft tests for `atomic`.
HTH
=> added 3 atomic perft test and 1 atomic move string test

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/chancellorboard.cpp, projects/lib/src/board/chancellorboard.h, projects/lib/src/board/modernboard.cpp, projects/lib/src/board/modernboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support Chancellor Chess and Modern Chess, chess variants for a 9x9 board, also in response to enhancement request #291.
_Chancellor Chess_ was introduced in 1887 by Benjamin R. Foster. Both sides have nine Pawns and a Chancellor (Bishop+Knight) piece starting on the f-file (next to the King). A King moves two squares to either the c-file or the g-file when castling. Pawns may (also) promote to Chancellor when reaching the final rank. 
Default FEN "rnbqkcnbr/ppppppppp/9/9/9/9/9/PPPPPPPPP/RNBQKCNBR w KQkq - 0 1" 
Using position setup via FEN one may e.g. replace Chancellor(s) and use Queen(s) instead in order to play related variants.
FEN "rnbqkqnbr/ppppppppp/9/9/9/9/9/PPPPPPPPP/RNBQKQNBR w KQkq - 0 1"![xm2](https://user-images.githubusercontent.com/6425738/32421600- …
=> support Chancellor Chess (9x9) and Modern Chess (9x9)

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/gryphonboard.cpp, projects/lib/src/board/gryphonboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR adds support of _Gryphon Chess_ by Vernon R. Parton, along with three related shape shifter chess variants.
_Gryphon Chess_ is also known as _Complicacious Chess [Multiple Kings]_. This variant was introduced by Vernon R. Parton, UK, in 1961 and amended in 1974.
Moved pieces (except for Kings) change their type at the end of a move. A Pawn becomes a Knight, a Knight transforms to a Bishop, Bishop changes to Rook, Rook to Queen, Queen to King. The Kings are omitted from the initial setup. A side must never have more than four Knights, four Bishops, four Rooks, and two Queens. These restrictions were made in order to play the game over the board using two complete sets of chess pieces (i.e. in most of all practical situations).
There can be fifteen Kings for a side, and giving mate …
=> support Gryphon Chess

projects/lib/src/board/westernboard.cpp
The Two Kings variant castling bug #304 is caused by a change I made in WesternBoard. I suggest to revert this. This should be good for all variants. I will observe whether the Giveaway variant will have problems. If so, the solution would be to fix the Giveaway implementation alone.
HTH
=> Revert changes in WesternBoard::removeCastlingRights, resolves #304

projects/lib/src/board/twokingseachboard.cpp, projects/lib/src/board/twokingseachboard.h
Include commoner(s) in the material count (valued as a major piece).
@ianfab This is the `cutechess-cli` I have used in my recent testing.
=> Fix two kings insufficient material adjudication

docs/cutechess-cli.6, projects/lib/src/board/chancellorboard.cpp, projects/lib/src/board/chancellorboard.h, projects/lib/src/board/modernboard.cpp, projects/lib/src/board/modernboard.h, projects/lib/tests/chessboard/tst_board.cpp
The proposed changes prevent both setup of and promotion to wrong piece types. Currently a Pawn can promote to Archbishop in _Chancellor Chess_ and to Chancellor in _Modern Chess_. These are illegal conversions.
`ModernBoard` and `ChancellorBoard` are now derived from `WesternBoard` instead of `CapablancaBoard`.
This patch also adds test cases for castling and promotion.
While there I made a small fix in the manual page.
=> Maintainance for ModernBoard and ChancellorBoard

projects/lib/src/pgngame.cpp
=> This patch adds the Variant tag to the minimal PGN output.

projects/lib/src/pgngame.cpp
like "Antichess" into the game database.
The GUI crashes with segmentation fault when importing a PGN game with some Capital letters in its Variant tag. This only occurs when the "Variant" tag matches a supported variant in lower case.
This patch supports the work done on #121.
=> Resolve problems when importing PGN data containing capital Variant tag values

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.cpp, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/courierboard.cpp, projects/lib/src/board/courierboard.h, projects/lib/src/board/shatranjboard.cpp, projects/lib/src/board/shatranjboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/tests/chessboard/tst_board.cpp
#This patch provides support of the medieval games _Shatranj_ and _Courierspiel_.
_Shatranj_ is a descendant of the old Indian game _Chaturanga_ and the predecessor of modern Chess. It spread from Persia via Turkey and Arab countries to Europe and was popular for almost a millenium. This game is slower than chess, There is no powerful Queen, but a Counselor (Ferz), who can only move one square diagonally. There no sliding Bishop, but a hopping Elephant (Alfil), which only can hop two squares diagonally. There are no Pawn double steps, and no castling moves. Giving mate or stalemate to the opponent King wins. Stripping the King of all his men also wins, if the opponent King does not immediately retaliate.
_Courierspiel_ is a game derived from Shatranj and was played in Central Europe …
=> Support medieval chess: Shatranj and Courier

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/gui/src/boardview/boardscene.cpp, projects/gui/src/boardview/piecechooser.cpp, projects/lib/src/board/board.cpp, projects/lib/src/board/board.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/seirawanboard.cpp, projects/lib/src/board/seirawanboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR is a suggestion to support _Seirawan Chess_ or _S-Chess_.
In 2007 Yasser Seirawan and Bruce Harper introduced a new variant of Standard Chess. Their intention was to reduce the draw rate by having Capablanca pieces but using the common 8x8 board. At start the standard chess set up is used. However, each side has in reserve a Knight+Bishop combination, called _Hawk_ (Archbishop in Capablanca Chess) and a Knight+Rook combination, called _Elephant_ (Capablanca Chess: Chancellor). One of these pieces has the option to enter the board on a square of the own base rank immediately after this square has been vacated for the first time. No piece can enter on a square that has been vacant before the move. Only one piece can enter per move. There is no obligation to use the reserve pieces at …
=> support Seirawan Chess (a.k.a. S-Chess)

projects/lib/src/tournament.cpp
Fixes a bug in the library where tournament pgn data are deleted before
the gameFinished signal is emitted, denying handlers access to data.
The fix deletes the pgn data immediately after sending the signal
instead.
=> Fix deletion of pgn data before signal emission

projects/lib/src/econode.cpp, projects/lib/src/pgngame.cpp, projects/lib/src/pgngame.h
Fixes a bug in the library where PgnGame::read() automatically creates
the opening tags (ECO, Opening, and Variation) while reading a file that
already contains those tags.  This creates a bug in
EcoNode::initialize(PgnStream&) which uses PgnGame::read() to create the
EcoNode tree from a PGN file.
=> Fix automatic creation of ECO tags while reading EcoNode file

projects/gui/res/chessboard/chessboard.qrc, projects/gui/res/chessboard/merida.svg, projects/gui/res/chessboard/merida.txt
This PR contains a SVG file with piece graphics derived from the original True Type Font by Armando H. Marroquin.
Derivative art work by Felix Kling has been used with his permission by the PyChess project.
I arranged the SVG single piece files into one file and added new piece graphics of Carrera (Capablanca) pieces and promoted pieces used e.g. for Crazyhouse.
This is intended to be released under license CC-BY-SA-4.0 international, which is designed to be compatible for usage with GNU General Public License V3.
I would like to get feedback from Felix Kling and Tamás,  @gbtami, to be sure they do not object. 
EDIT: This relates to user request #137 .
=> Merida pieces

projects/gui/src/mainwindow.cpp, projects/gui/src/mainwindow.h, projects/lib/src/chessgame.cpp, projects/lib/src/chessgame.h
This adds a menu item to the "Game" menu of the GUI with the functionality to resign a game for a human player. When the new item "Resign" is selected, the side to move resigns the game. However, if the side to move is not a human (local) player then the side to wait resigns the game. If both sides are played by engines, no resignation will be triggered - and the menu item will be rendered inactive anyway.
In addition, the menu items for game adjudication are disabled if the game shown in the active tab is finished.
=> Add function to resign a game via GUI menu item

projects/lib/src/board/westernboard.cpp, projects/lib/tests/chessboard/tst_board.cpp
The half-move counter continues counting up for castling moves. I was surprised to hear that. Indeed, FIDE rules 5.2 and 9.3 and the specification of PGN and FEN, 16.1.3.5 mean that in standard chess pawn moves and captures reset the counter, castling moves do not. I checked and Xboard and PyChess indeed count correctly.
This is also relevant for all FIDE derivative variants (derived from `WesternBoard` and having castling). Drop moves are a different matter, FIDE rules do not specify drop moves.
I suggest to insert a comment into WesternBoard and leave out the counter reset for castlings.
This has consequences for the testing suite, so I adapted the FEN test strings.
[Laws of Chess](http://www.fide.com/FIDE/handbook/LawsOfChess.pdf)
[PGN …
=> Continue fifty-moves counting when castling.

projects/gui/src/cutechessapp.cpp, projects/gui/src/mainwindow.cpp, projects/gui/src/mainwindow.h, projects/gui/src/settingsdlg.cpp, projects/gui/ui/settingsdlg.ui
This PR suggests adding choices for the name representation of human players to the GUI
- Add option to use full user name instead of login name
- Add option to display sides of players on chess clock
- Checkboxes to configure these options in General Settings
References: Issues #139 and #110 .
=> User Name Options

README.md, cutechess.pro, dist/windows_setup.iss, translations/cutechess_zh_CN.ts
Here comes a translation file for zh_CN localization. It works when the executable is placed like this:
```
├ translations/
│  ├ cutechess_[language_code_1].qm
│  └ cutechess_[language_code_2].qm
└ cutechess-gui
```
To maintainers: please compile with `lrelease` and include the `.qm` file with the `translations` directory in release packages, excluding the `.ts` file.
=> Add zh_CN localization.

projects/gui/src/newgamedlg.cpp, projects/gui/src/settingsdlg.cpp, projects/gui/ui/settingsdlg.ui, projects/lib/src/chessplayer.cpp, projects/lib/src/chessplayer.h, projects/lib/src/humanbuilder.cpp, projects/lib/src/humanbuilder.h, projects/lib/src/humanplayer.cpp, projects/lib/src/humanplayer.h
This adds a checkbox to the General Settings of the GUI. The user may configure whether a human player can play after timeout or forfeit games on time. The configuration is saved and comes into action _for new games only_ (remark: behaviour of updated version changed) immediately when changing the status of the checkbox.
I refrained from using a per-game configuration. Nevertheless, I hope this is useful.
=> Add GUI configuration: human player can/cannot play after timeout

projects/lib/tests/chessboard/tst_board.cpp
This PR adds 3 results tests and 2 move string tests to the chessboard test suite.
=> Add tests for fifty-move rule

projects/lib/src/board/giveawayboard.cpp, projects/lib/src/board/giveawayboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h
This patch removes castling rights for `GiveawayBoard` by invoking a new method in `WesternBoard`.
This change has been pending after corresponding code for Giveaway was removed from WesternBoard in #305. In contrast to the older (and reverted) solution this patch is not expected to influence other variants.
=> Giveaway Chess: remove castling rights if King is captured on base rank

.travis.yml
Bump Travis QT versions to the latest available (5.6.3 and 5.9.4) and add a build with QT 5.10.1. QT 5.10.1 builds fine on my machine (Arch Linux) but I guess we'll have to see what Travis thinks about it...
=> Bump Travis QT versions and add 5.10.1

projects/gui/src/mainwindow.cpp, projects/gui/src/mainwindow.h
This PR adds a menu item "Copy PGN" to the "Game" Menu of the GUI. The action copies the current Portable Game Notation of the game in the active tab to the clipboard.
This supports feature request #367.
=> Adding option to copy notation of current game (main window) to clipboard

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/cli/src/main.cpp, projects/gui/src/gamesettingswidget.cpp, projects/gui/ui/gamesettingswidget.ui, projects/lib/src/gameadjudicator.cpp, projects/lib/src/gameadjudicator.h
This PR adds support of length-based draw adjudication to the library, the CLI and the GUI.
This feature has been requested in #325.
It adds a new option `-maxmoves n` to CLI in order to limit the number of moves in a game:
longer games are adjudicated as drawn.
A corresponding spin box supports the game configuration of the GUI.
=> Add support for length-based draw adjudication to the library

projects/gui/src/movelist.cpp
This patch prevents the text cursor from escaping the visible area.
=> Scrolling of move list to follow the text cursor. Resolves #292.

projects/lib/src/board/board.cpp
I noticed that the GUI's FEN validator accepted a position with Makruk piece types for standard chess (forgot to select the variant).   
`Board::setFenString` should return false when finding unknown symbols. My older patch 2419a86 caused the problem. This PR fixes it.
Test examples for standard chess:
`8/4k3/3MM3/4K3/8/8/8/8 b - - 0 1` passed validation in GUI but should fail
`8/4k3/3**3/4K3/8/8/8/8 b - - 0 1` dito
=> Fix problem with unknown symbols passing setFenString.

projects/lib/src/pgngame.cpp, projects/lib/src/pgngame.h
The duration of a game is given in the format "hh:mm:ss".
=> Add PGN tag [GameDuration], CR #374:

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/aseanboard.cpp, projects/lib/src/board/aseanboard.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/makrukboard.cpp, projects/lib/src/board/makrukboard.h, projects/lib/src/board/oukboard.cpp, projects/lib/src/board/oukboard.h, projects/lib/src/board/shatranjboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR adds support for South-East Asian chess:
- Makruk  (Thai Chess),
- Ouk Chatrang (Cambodian Chess)
- Kar Ouk variant
- ASEAN-Chess
_Ouk Chatrang_ (Cambodian Chess, Ouk Khmer) and _Makruk_ (Thai Chess) are hugely popular in their home countries. These game styles have emerged from the origins of chess many centuries ago.
The implementation of `MakrukBoard` is based on `ShatranjBoard`, because all pieces basically move like their counterparts in Chaturanga and Shatranj. One Exception is the Khon piece, which replaces the Alfil (Elephant, medieval Bishop). It can move one square diagonally or one square straight ahead. The pawns start on the third rank and promote to Met (Ferz, Advisor, medieval Queen) like in Shatranj, however the promotion already takes place …
=> Add support for South-East Asian Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.cpp, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/grandboard.cpp, projects/lib/src/board/grandboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/src/xboardengine.cpp, projects/lib/src/xboardengine.h, projects/lib/tests/chessboard/tst_board.cpp
- Add support for multi-digit notations
- Add extension to support CECP quirk for games with 10 ranks
This patch supports _Grand Chess_, a 1984 chess variant by Christian Freeling on a 10x10 board. This variant uses piece types known from _Capablanca Chess_. The starting position resembles the position of Embassy Chess. However, both sides have 10 pawns on their _third_ rank, the rooks are at the corners of the board, and the rest of the pieces on their second rank.
This variant has initial double step option for pawns and en passant captures. Pawns can only be promoted to an own captured piece. Pawn promotion is optional when reaching rank eight or nine but mandatory when reaching the last rank. If promotion is impossible, then the pawn will not be able to advance to the tenth rank. It …
=> Support Grand Chess

projects/gui/res/chessboard/chessboard.qrc, projects/gui/res/chessboard/makruk.svg, projects/gui/res/chessboard/makruk.txt
This PR adds a set of pieces designed by Peter Thomson (@Cajone).
They are intended to be used for Makruk and related South-East Asian variants like Ouk Chatrang and Karouk.
Boat and Advisor glyphs were adapted for cutechess autoscaling.
_Initial position of Makruk with the Makruk piece set by @cajone - taken from PyChess and arranged for Cutechess: prevent glyphs of Boat (Rua) and Advisor (Met) from scaling much._
=> Makruk Pieces by Peter Thomson

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/makrukboard.cpp, projects/lib/src/board/sittuyinboard.cpp, projects/lib/src/board/sittuyinboard.h, projects/lib/src/board/westernboard.cpp, projects/lib/tests/chessboard/tst_board.cpp
This PR adds support for Sittuyin, the traditional chess of Myanmar. The code is based on the Makruk implementation of PR #348.
Sittuyin is the traditional variant of chess in Myanmar. It is an old game (9th century) closely related to Makruk and Chaturanga. There has been a wide variety of local or temporary rules.
Each side begins with four Pawns on the left side on their third rank and four Pawns on the right side on their fourth rank.
In the initial phase of the game the red side places their pieces behind their Pawns. After that the black side places their pieces. Rooks must be placed on the back rank ~~and must not start on the opponent king's file if only Pawns are in between~~. After all pieces have been placed the red side makes their first move.
Sittuyin pieces move like Makruk …
=> Support Sittuyin (Myanmar Chess, Burmese Chess)

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/aiwokboard.cpp, projects/lib/src/board/aiwokboard.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/makrukboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR adds support for _Ai-Wok_, a variant of Makruk where the Met (Advisor) is replaced by a powerful piece, the Ai-Wok, which has all movements of Rook (Rua), Knight (Ma), and Advisor (Met).
Pawns promote to Ai-Wok when reaching their sixth rank.
This lightweight implementation is based on `MakrukBoard`. Only the evaluation of material has to be adapted. 
When using the defaultFenString `"rnsaksnr/8/pppppppp/8/8/PPPPPPPP/8/RNSKASNR w - - 0 1"`the standard chess counting is in action while the Makruk counters have no effect.
The implementation has been tested using _Sjaak II 1.4.1_, _Fairymax 5.0b_ and the new _Fairy-Stockfish_ implementation.
=> Support Ai-Wok, a Makruk variant

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/losalamosboard.cpp, projects/lib/src/board/losalamosboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR adds support of Los Alamos Chess.
Los Alamos chess is a variant of standard chess which is played on a 6x6 board. This variant has no bishops, no pawn double steps, and no castling. It was introduced in 1956 by Paul Stein, Mark Wells, and
others with the first chess-like program on the MANIAC I computer of Los Alamos Scientific Laboratory. Due to the limited resources of the computer it was not yet practical to implement standard chess.
This implementation has been tested with _Sjaak II 1.4.1_, _NebiyuAlien_, and _Fairy-Stockfish_.
=> Support Los Alamos Chess

projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR amends support for the FEN full move counter.
WesternBoard::vSetFenString currently ignores the full move field in a given FEN. This implementation reads the full move counter and corrects the FEN notation (move number) for black starting positions and odd history sizes.
The problem:
consider a (black to move) setup-position (obtained from 1. e4)
FEN  `rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1`
in cutechess we obtain after playing 1. ... e5
an incorrect FEN ` rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 1`
the correct FEN is `rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2`.
HTH
=> Support FEN full move counter

projects/gui/src/mainwindow.cpp
Small patch: Suggestion to get the variant information from the targeted (template) game.
I tested this with standard chess, crazyhouse and grid chess.
A new game might also "inherit" other properties from the targeted game, like time control settings, engine setups, etc. "Paste & Inherit".
=> Pasting general FENs to targeted variants

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/gui/src/tournamentsettingswidget.cpp, projects/gui/ui/tournamentsettingswidget.ui, projects/lib/src/pyramidtournament.cpp, projects/lib/src/pyramidtournament.h, projects/lib/src/src.pri, projects/lib/src/tournamentfactory.cpp
This PR supports a  "pyramid tournament". This is essentially a round-robin tournament where the sequence of pairings is different. Every listed player meets all of their predecessors in the list, in sequence.
Example: Participants 0, 1, 2, 3. 
First, Player 0 will play against nobody - skipped.
Then player 1 will be paired against player 0 (round 1).
After that player 2 will play 0, then play against 1 (round 2).
Finally, player 3 will play 0, 1, and at last 2 (round 3).
The CLI options `-games n` and `-rounds m` and their counterparts in the GUI can be used to further specify the tournament. They work as for round-robin tournaments.
=> Support Pyramid Tournament Type

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/cli/src/main.cpp, projects/gui/src/newtournamentdialog.cpp, projects/gui/src/tournamentsettingswidget.cpp, projects/gui/src/tournamentsettingswidget.h, projects/gui/ui/tournamentsettingswidget.ui, projects/lib/src/tournament.cpp, projects/lib/src/tournament.h
This patch adds the option to omit unfinished games from PGN output. When stopping a tournament also stalled and disconnected games are left out.
The CLI has an additional optional parameter for `-pgnout` :
```
-pgnout FILE [min][fi]
Save the games to FILE in PGN format. Use the 'min'
argument to save in a minimal/compact PGN format. Only
finished games are written when argument 'fi' is set.
```
TournamentSettingsDialog of the GUI has an additional checkbox "Save unfinished games".
The default behaviour is unchanged: cutechess GUI and CLI will write all PGN games.
This resolves #230 .
=> Add option to discard unfinished games from PGN output

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/almostboard.cpp, projects/lib/src/board/almostboard.h, projects/lib/src/board/amazonboard.cpp, projects/lib/src/board/amazonboard.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/chigorinboard.cpp, projects/lib/src/board/chigorinboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR comprises of 3 patches each adding support of one chess variant.
These are lightweight implementations.
_Almost Chess_: This variant by R. Betza replaces the Queen by a Chancellor piece with Rook and Knight movements.
_Amazon Chess_: Here the Queen has additional powers of a Knight. This is an established variant (16th century) and  has been the standard way to play chess in Russia and Georgia.
_Chigorin Chess_: White has no pieces with Bishop movement but four Knights and one Chancellor with Rook and Knight movements. Black has no pieces with Knight movement but four Bishops
and one Queen. Pawn can only promote to piece types present at the start, so no Queen for White and no Chancellor for Black.
The variants have been tested with _Fairy-Stockfish_ (all), and with _Sjaak II_ …
=> Support Almost Chess, Amazon Chess, and Chigorin Chess

projects/lib/src/xboardengine.cpp
As long as cutechess has an arbiter function, illegal moves are not (read: should not be) transmitted to engines. So a claim of an illegal move should not be valid. At present, without adjudication the claiming engine waits and finally forfeits on time.
This patch avoids the wait and adjudicates against the CECP engine claiming an illegal move. This resolves #109 .
=> CECP engine forfeits on claim of illegal move

projects/lib/src/chessgame.cpp
This PR resolves problem #408.
=> Set PGN tags for White and Black when starting a game. Resolves #408.

projects/gui/src/gamedatabasedlg.cpp, projects/gui/ui/gamedatabasedlg.ui
This patch adds a variant label to the GameDatabaseDialog. It will only be visible if the Variant tag of the currently selected game is not empty.
It helps browsing mixed databases with games of various chess variants.
=> Display variant label in GameDatabaseDialog

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/rifleboard.cpp, projects/lib/src/board/rifleboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR adds support of _Rifle Chess_ and _Shooting Chess_.
These variants of chess have a different way to capture pieces: An attacking piece removes (shoots) an opponent piece without replacing it.
Shoot Chess or Shooting Chess is a variant of Rifle Chess: It is obligatory to make a capturing move if possible.
This implementation has been tested by manual play. I hope this is useful.
=> Support Rifle Chess and Shooting Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/codrusboard.cpp, projects/lib/src/board/codrusboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR supports The Game of Codrus, a predecess of Losing Chess.
The Game of Codrus has been described in J. Brede's Alamanach, Altona, then Denmark 1844.
It is named after the Athenian King Codrus who sacrificed himself to save his people (1068 BC).
In this chess variant, the King has no royal powers, so there is no check and the King can be
captured. Castling is allowed. If a side can capture then they must make a capture move.
**The side whose King is captured wins.**
Rules: : J. Brede (1844): Almanach für Freunde vom Schachspiel, Altona, Denmark: J. F. Hammreich. p. 82f. (in German language) retrieved from: http://www.binnewirtz.com/Brede.htm.
Also see Pritchard, D. B. (2007). Beasley, John, ed. The Classified Encyclopedia of Chess Variants. Harpenden, UK: John Beasley. ch. 10.9. …
=> Support The Game of Codrus, a Losing Chess variant

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/hoppelpoppelboard.cpp, projects/lib/src/board/hoppelpoppelboard.h, projects/lib/tests/chessboard/tst_board.cpp
This patch adds support for two leightweight chess variants with hybrid piece movement. These variants are known at least since the 1920s.
Hoppel-Poppel Chess is standard chess but with modified Bishops and Knights. The Bishop captures like a standard Knight but else moves as usual. This piece configuration is called `Biskni`. The Knight captures like a standard Bishop but makes their usual hops when not capturing. This piece is called`Knibis`. In the endgame these hybrid pieces seem to be weaker than Bishop or Knight.
New Zealand Chess is similar. The Bishops are normal Bishops, but here the Rooks and the Knights are hybrids called `Rookni` (R moves and N captures) and `Kniroo` (N moves and R captures). The Rooknis can participate in castling. In the endgame these hybrid pieces are …
=> Support Hoppel-Poppel and New Zealand Chess

projects/cli/src/main.cpp, projects/gui/ui/timecontroldlg.ui, projects/lib/src/timecontrol.cpp, projects/lib/src/timecontrol.h
This PR is intended to fix problem #433.
The node limit property of time control now is of type `qint64` instead of `int`. So the upper limit of 2^31 - 1 nodes for lib and CLI is lifted to 2^63 - 1 nodes and practically out of reach.
The node limit in the GUI however, has only been increased twenty-fold from 99999999 to 2 ** 31 - 1.
HTH
=> Use 64-bit node limits

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/jesonmorboard.cpp, projects/lib/src/board/jesonmorboard.h, projects/lib/tests/chessboard/tst_board.cpp
Jeson Mor is a board game from Mongolia. There are nine knights per side and no other pieces. Initially all knights are lined up on their sides' first rank of a 9x9 board.  Leaving the central square e5 or capturing all opponent pieces wins.
Note: `JesonMorBoard` adjudicates early when a side occupies the cental square and has the move or the central piece cannot be captured by the opponent.
This implementation has been tested by manual play and with the [Fairy-Stockfish](https://github.com/ianfab/Fairy-Stockfish) engine.
I hope ths is useful.
=> Support Jeson Mor

projects/lib/src/board/sittuyinboard.cpp, projects/lib/src/board/sittuyinboard.h, projects/lib/tests/chessboard/tst_board.cpp
Such a move is not legal (rule 3.9 c.5).
Resolves #448
Adjudicate stalemate as draw (rule 5.2 a)
Resolves #449
Thanks to @gbtami
=> Sittuyin: Prevent discovered check by Pawn promotion.

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/cli/src/main.cpp, projects/gui/src/gamesettingswidget.cpp, projects/gui/ui/gamesettingswidget.ui, projects/lib/src/gameadjudicator.cpp, projects/lib/src/gameadjudicator.h
This PR resolves #385.
The CLI option `-resign` now has a new optional parameter `twosided`. When set to _true_ it activates two-sided resign adjudication: In addition to the conditions of the normal (single-sided) resign adjudication the winning side's scores must be at least _SCORE_ centipawns above zero for at least _COUNT_ consecutive moves.
So the proposed usage for two-sided adjudication is
`cutechess-cli ... -resign movecount=4  score=650 twosided=true  ...`.
Normal, single-sided resignation works as before.
In the GUI there is a new group of radio buttons to select either normal (single-sided) or two-sided resignation score adjudication.
----
Original text:
The option `-resign2`  is added to the CLI. The new option activates two-sided resign adjudication. It has no parameters of …
=> Option to use two-sided scores for resign adjudication

README.md
Hello,
thank you for this cool GUI which also supports the main chess variants.
A friend of mine had trouble building  cutechess for mac and because there's no official release for mac,
I thought it could be useful to update the build instructions for mac on your wiki-page.
Unfortunately there's no proper way to create a pull request for wiki pages right now:
* https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github
That's why I post the instructions which worked on his system here so you can include this in your wiki:
I also added a link to the wiki page in the main readme.
* https://github.com/glinscott/fishtest/issues/13
Install Homebrew:
```
$ ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
``` 
Install Qt:
```
$ brew install qt
```
Get …
=> Added link to wiki-page for build instructions and simpler build instructions for mac

projects/gui/src/evalwidget.cpp
This small patch shows search speed in (unity) nps instead of knps when speed is below 10000 nodes per second.
Resolves request #481.
=> Give search speed in nps for values below 10000, else in knps.

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.cpp, projects/lib/src/board/board.h, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/gustavboard.cpp, projects/lib/src/board/gustavboard.h, projects/lib/tests/chessboard/tst_board.cpp
This is a suggestion to support the chess game of Gustav III's of Sweden, resolving feature request #467.
In this chess variant there are four new squares attached to sides of the chess board outside of the Rooks. At the start of the game each of these squares is occupied by a powerful Adjutant-General (Amazon, with Queen and Knight movements). Squares a2-a7 and j2-j7 are occupied by wall  pieces so they cannot be used by the regular pieces. Standard chess rules apply. A Pawn can promote to Adjutant-General.
Wall squares are each denoted by an asterisk '*' in FEN (maintaining xboard-compatibility).  
It was necessary to extend `Board::fenString` and `Board::setFenString` for this.
The starting position is given by 
`arnbqkbnra/*pppppppp*/*8*/*8*/*8*/*8*/*PPPPPPPP*/ARNBQKBNRA w KQkq - 0 …
=> Support Gustav III's Chess

projects/lib/src/tournament.cpp
Reason for this suggestion is that it's very rare that Elo estimations have error bars low enough to justify a precision of two decimal places.
=> Rounding Elo to one decimal place.

projects/gui/ui/tournamentsettingswidget.ui
This patch adds some short descriptions of tournament types to the GUI.
Resolves #452
=> Add tooltip hints for tournament types

projects/lib/src/chessengine.cpp, projects/lib/src/chessengine.h, projects/lib/src/uciengine.cpp
This small patch causes output of some more information in case of illegal PV moves.
Resolves #471
=> Add id number of engine issuing an illegal PV move, and print PV line

docs/cutechess-cli.6, projects/cli/res/doc/help.txt
While in fathom source code probe_root calls probe_dtz, probe_dtz actually ends up calling probe_ab, which calls probe_wdl_table.
Without WDL tables this fails, which cascades upwards to probe_root failing.
WDL files should be the expected minimum - dtz files for syzygy are technically not complete without the corresponding WDL files.
=> Wdl not dtz should be the minimum required for adjudication.

projects/gui/src/boardview/boardscene.cpp
resolves #491 
One might possibly want to retire Board::variantHasOptionalPromotions() later.
=> Test whether declined promotion move exists

projects/gui/src/enginemanagementwidget.cpp
This is a small patch to update the engine count shown in the engine management widget.
=> Update engine count label when adding or removing engines

projects/lib/src/board/sittuyinboard.cpp, projects/lib/src/board/sittuyinboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR only affects SittuyinBoard and consists of three patches:
1. Implementation of Sittuyin rule 3.9c.7 (Maung Maung Lwin: How to play Myanmar Traditional Chess, p. 8): If promotion moves are the only legal moves to avoid a stalemate then the weaker side may claim a draw. So cutechess will adjudicate a draw with this software patch.
In this situation white to move may claim a draw. FEN: 1k4PK/3r4/8/8/8/8/8/8[-] w - 0 0 1
2. There is a problem with pawn promotions in engine play. This patch avoids wrong decoding of promotion moves in LAN format (by then throwing away the result of moveFromSanString for promotion moves in SittuyinBoard!).
3. A problem in `SittuyinBoard::isLegalPosition` gets obvious when using a debug compile and running the chessboard test suite: The move history must …
=> Improvements of SittuyinBoard

projects/lib/src/gauntlettournament.cpp, projects/lib/src/gauntlettournament.h, projects/lib/src/tournament.cpp, projects/lib/src/tournament.h
Resolves #501
Alternative 1 - "Small Solution"
This PR introduces a new flag `m_newRound` to `GauntletTournament`. The `Tournament` class is amended by a virtual method which indicates whether a new opening should be used for the next pair of players. This affects the behaviour of CuteChess only for gauntlet tournaments.
Note: A new opening will still be used when the number of repetitions played reaches the number of specified repetitions (equals 1 if option `-repeat` is not used, 2 for `-repeat` without parameter). So it is necessary to use `-repeat n` with a **sufficiently large n** to play an entire round with the same opening.
Example: A gauntlet of Engine1 against Engine2 and Engine3 with 4 games per encounter requires at least `-repeat 8`: 4 games per encounter * 2 encounters (1 vs …
=> For gauntlet tournaments keep same openings within rounds

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/cli/src/main.cpp, projects/lib/src/tournament.cpp, projects/lib/src/tournament.h
Resolves #501
(library and CLI).
Alternative 2 - "More general solution"
This patch adds a parameter _policy_ to the CLI option `-openings`,e.g. `policy=default`.
It can have one of three values:
_default_: Use a new opening when a new encounter (pair of players) starts or the specified number of repetitions is reached. Cutechess behaves as before - except for some cases of incommensurable combinations n,m of -repeat n and -games m.
_encounter_  uses a new opening only for a new encounter.
_round_ shifts to a new opening only when a new round starts.
The _RoundPolicy_ currently depends on the (tag) round counters of the tournament types. These are not in sync with the schedule repetition counters controlled by the -round n option of the CLI or the corresponding `m_roundsSpin` SpinBox of …
=> Introduce policies when to pick the next opening in tournaments

projects/gui/src/gamesettingswidget.cpp
Small fix because EPD opening books do not work anymore in the GUI. 
(Qt::CaseInsensitive has value 0.)
=> Fix problem reading EPD openings

projects/lib/src/board/sittuyinboard.cpp, projects/lib/tests/chessboard/tst_board.cpp
This fix implements missing Sittuyin rule 3.9 c.4.
Thanks to @teakado, @gbtami and @ianfab for pointing this out.
Ref.: https://github.com/ianfab/Fairy-Stockfish/issues/14
=> Sittuyin: Do not allow promotions to attack an opponent piece directly.

projects/lib/src/timecontrol.cpp
This is a small fix. The SettingsGroup in writeSettings has no termination.
=> End the SettingsGroup in TimeControl::writeSettings

projects/gui/src/mainwindow.cpp
This small patch for the GUI assigns shortcut _CTRL-F_ to flipping the view of the board.
Related to #387
=> New shortcut for board flipping

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/gui/src/tournamentsettingswidget.cpp, projects/gui/ui/tournamentsettingswidget.ui, projects/lib/src/gauntlettournament.cpp, projects/lib/src/gauntlettournament.h, projects/lib/src/tournament.cpp
Library, CLI and GUI
Resolves #488
In the CLI, the `-seeds n` option specifies the number of seeded (first) players who play gauntlet against the rest. Only the first player plays against the rest if the option is omitted (the default)  and also for `-seeds 0`, and `-seeds 1`.
In the GUI the seeds spinbox is used to specify the number of gauntlet players.  Standard gauntlet tournaments with the first player against the rest result from both values 0 and 1.
The number of gauntlet players is bounded by 1 and the total count of tournament players minus 1.
=> Extend gauntlet tournaments to multiple seeded players

projects/lib/src/board/oukboard.cpp, projects/lib/src/board/oukboard.h, projects/lib/tests/chessboard/tst_board.cpp
A King must not capture with the initial leap.
An Advisor (Queen) may capture with its initial leap.
Also, an inconsistency between move generation and check detection has been fixed.
Thanks to @ianfab for bringing this up.
=> Ouk Chatrang: Correction of rule implementation

projects/gui/src/newtournamentdialog.cpp, projects/gui/src/tournamentsettingswidget.cpp, projects/gui/src/tournamentsettingswidget.h, projects/gui/ui/tournamentsettingswidget.ui
This change in the GUI corresponds to CLI's -noswap option (CLI feature request #95).
This resolves #321 for gauntlet tournaments (i. e. player 0) and also for the first player of a round-robin tournament (given the current tournament game sequence).
=> Add checkbox to Tournament Settings to enable/disable side swap

projects/lib/src/uciengine.cpp
This PR is a bugfix for UCI code specific to the `UCI_Variant` option. The bug happens with any engine that supports `UCI_Variant` combo option with the `standard` value. When playing standard chess matches through cutechess-cli, cutechess will send `setoption name UCI_Variant` to the engine without an actual value. However, in the UCI specification, only button-type options can be set without a value. Doing it for combo-type options is a bug, and causes some engines to crash.
=> Fix issue where UCI_Variant is sent without a value.

projects/gui/src/gameviewer.cpp, projects/gui/src/gameviewer.h, projects/gui/src/settingsdlg.cpp, projects/gui/ui/settingsdlg.ui
This patch adds a checkbox to the General section of Settings. It enables or disables auto flipping the board after each move in human vs human games.
Discussed in #387
=> GUI: option to enable automatic flipping of board for human vs human games

projects/gui/src/evalhistory.cpp, projects/gui/src/evalhistory.h
The score graph for games set-up from Black starting positions currently is inverted (Fig. 1). This patch fixes the assignment of odd and even plies  (Fig. 2).
_Figure 1: Black wins. The game started with a set-up position and Black having the move. The score graph suggests a win for White_
_Figure 2: Black wins. The game started with a set-up position and Black having the move. With the fix the score graph is consistent with game scores._
=> Fix display of evaluation history for games with Black starting positions

projects/lib/src/xboardengine.cpp
This patch fixes a bug I introduced last year into the CECP (xboard) mate score calculation. Only _new style_ mate scores for the winning side are affected. Currently the transformation of the mate scores for the winning side is off one ply e.g. 999998 (+M2) instead of 999999 (+M1).
=> Fix CECP mate scores for winning side

projects/lib/src/epdrecord.cpp, projects/lib/src/epdrecord.h
This PR fixes an issue where halfmove clocks and fullmove numbers from epd opening files are ignored.
A position in epd format doesn't store halfmove clock and fullmove number in the fen part, but they can still be specified (optionally) through the hmvc and fmvn opcodes. Use this when converting epd to fen.
As a side effect, if hmvc and fmvn are not set, we now return a fen with halfmove clock and fullmove number set to 0 and 1, since returning a fen without those is not strictly correct.
I've checked as carefully as I can that there are no assumptions anywhere that EpdRecord::fen() doesn't return a full fen, so hopefully this change doesn't break anything. As mentioned, the new behavior is more correct anyway.
=> Read halfmove clock and fullmove number from epd opening files

projects/lib/src/openingsuite.cpp
Fixes #550 and Fixes #552
* allow the start option to be larger than the number of positions in the book file, using wrapping semantics. Makes it easier to use (no need to know the size of the book, or to restart after N games where N is larger than the size of the book)
* fix the start option to work with epd opening books, right now it was ignored/overwritten.
* introduce the start option to work not only with sequential but also with random order, picking the appropriate location in the random stream.
* fix the generation of the random permutation of the book.
tested to behave as expected looking at a couple of corner cases (start=N, with N=size of the book, size + 1, size + N, etc)
Will also help fixing https://github.com/glinscott/fishtest/issues/478
=> Fix and generalize the book start option.

projects/lib/src/board/seirawanboard.cpp, projects/lib/src/board/seirawanboard.h
In S-chess the insertion of reserve pieces must not be used to block check.
Resolves #569
=> Fix problem with ignored pins in S-Chess

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/cli/src/main.cpp, projects/lib/src/tournament.cpp, projects/lib/src/tournament.h
This patch introduces an option `-reverse` to the CLI, which reverses the colour assignment in a tournament.
E.g. the sequence
`Player A -  Player B, Player C - Player D`
would become
`Player B - Player A, Player D - Player C`. 
For gauntlet tournaments, `-reverse` together with the options `-noswap` and  `-games m` has the gauntlet player play `m` games per round all with Black (instead of White) against any opponent in the list.
Thus resolves #520.
=> Introduce flag to reverse schedule for sides in CLI

docs/cutechess-cli.6, projects/cli/res/doc/help.txt, projects/lib/src/board/board.pri, projects/lib/src/board/boardfactory.cpp, projects/lib/src/board/shogiboard.cpp, projects/lib/src/board/shogiboard.h, projects/lib/tests/chessboard/tst_board.cpp
This PR supports Shogi, a Japanese form of chess where captured pieces can be brought back ("dropped") into the game, It is played on a 9x9 board. The piece set traditionally consists of
flat five-sided pieces with their names written on them, but this implementation uses the standard piece set of CuteChess.
**Rules:**
Shōgi has eight types of original pieces. Either side starts with a set of 9 x Pawn (on the third rank), 2 x Lance, 2 x Knight, 2 x Silver (General), 2 x Gold (General), 1 x Bishop, 1 x Rook, 1 x King.
The latter three types move like in standard chess. The Pawn moves and captures 1 square straight forward. The Lance moves and captures like a Rook, but only forwards. Similarly, the Knight leaps like a chess Knight, but only in the two forward directions. The Silver goes one …
=> Support Shogi (Japanese Chess)

projects/lib/src/timecontrol.cpp
Achieves more compliance with FIDE rules
[FIDE rules, Glossary, p. 31](http://rules.fide.com/images/stories/Laws_of_Chess_2018_-_EB_approved_-_clean_version.pdf)
> increment: 6.1. An amount of time (from 2 to 60 seconds) added from the start before each
move for the player. This can be in either delay or cumulative mode.
E.g. for 5 Minutes with 3 seconds increment the clocks would start at 5:03 instead of 5:00.
Resolves #451.
Book moves still are not awarded increments in order to stabilize testing conditions.
=> Also add time increment before the first move (TimeControl::initialize)

projects/gui/src/timecontroldlg.cpp, projects/gui/src/timecontroldlg.h, projects/gui/ui/timecontroldlg.ui
This patch adds initial support of the new hourglass time control to the GUI.
A new radio button is added to the time control dialog.
Reference: Feature request #273
This implementation does not add a textual or graphical indicator to the clock.
Such an indicator may be useful for extensions like hourglass mode or paused games.
This implementation is independent of a possible protocol update for engines.
It should work for existing engines and human players.
=> GUI: Add hourglass time control

projects/lib/src/board/aseanboard.cpp, projects/lib/src/board/aseanboard.h, projects/lib/src/board/makrukboard.cpp, projects/lib/src/board/makrukboard.h, projects/lib/src/board/sittuyinboard.cpp, projects/lib/src/board/sittuyinboard.h
In _Makruk_ and _Ouk_ the weaker side initially adds the total number of pieces on the board to their move count. However, in _Sittuyin_ and _ASEAN_ the bare king move counting starts with no offset.
Ref.: Article 5e of ASEAN chess rules https://aseanchess.org/laws-of-asean-chess/ and Article 5e of Sittuyin rules.
=> Fix the initial ply count for bare king in ASEAN and Sittuyin

docs/cutechess-cli.6, projects/cli/res/doc/help.txt
The cutechess CLI expects to use the variant name `ai-wok`, while the docs say `aiwok`. This PR should make the naming consistent.
=> Fix ai-wok variant name in docs

projects/lib/src/uciengine.cpp
This is a workaround until the root cause is solved.
Resolves #563 .
=> Fix wrong illegal move claims when using UCI with variants kinglet and extinction

projects/gui/src/newtournamentdialog.cpp, projects/gui/src/tournamentsettingswidget.cpp, projects/gui/src/tournamentsettingswidget.h, projects/gui/ui/tournamentsettingswidget.ui
This patch adds a checkbox `Reverse schedule` to the tournament settings. If checked, the color schedule for the tournament is reversed, i. e. a sequence` PlayerA vs PlayerB, PlayerC vs PlayerD, ...` is transformed into `PlayerB vs PlayerA, PlayerD vs PlayerC ... `. The CLI already has the option `-reverse` to do this.
When swapping of sides is deactivated a gauntlet player then plays a sequence of games with Black instead of White.
Completion  /wrt feature request, resolves #520, resolves #521 .
@Oragonon: I forgot the request was related to the GUI, not the CLI.
=> GUI equivalent to the CLI option -reverse to reverse schedule for sides

projects/gui/src/movelist.cpp, projects/gui/src/movelist.h
This patch adds an action to toggle the visibility of move comments in the move list. The action is triggered by key "C" or by the "Toggle Comments" item of the context menu.
Resolves #145
_Move list with and without move comments_
=> Option to hide comments in move list

projects/gui/src/boardview/boardscene.cpp, projects/gui/src/boardview/boardscene.h, projects/gui/src/settingsdlg.cpp, projects/gui/ui/settingsdlg.ui
In SettingsDialog add spin box to choose move animation speed.
Add checkbox to enable or disable move arrows.
Resolves #207
Resolves #458
=> GUI: Configure move animation speed and hiding of move arrows

projects/gui/src/gamesettingswidget.cpp
Replace obsolete `signal QComboBox::currentIndexChanged(const QString &`) by
`signal QComboBox::currentTextChanged(const QString &)` for Qt-6 and Qt-5 compatibility. The former signal has been dropped from Qt-6. 
Tested for Qt-5.9.5. The variant change is reflected in the according choice of engines.
Resolves #703 .
=> Replace obsolete signal QComboBox::currentIndexChanged

CMakeLists.txt
Provide an `install` target with CMake.
I'm unsure whether the `engines.json` manual should be renamed to `cutechess-engines.json`.
=> cmake: provide `install` target

projects/lib/src/board/board.cpp, projects/lib/src/board/board.h, projects/lib/src/board/westernboard.cpp, projects/lib/src/board/westernboard.h, projects/lib/src/chessplayer.cpp
A game is drawn in case of a timeout if the opponent has no means to give checkmate by any regular sequence of moves (Ref.: FIDE rule 6.9). Cutechess currently adjudicates a loss on timeout anyway.
This patch resolves simple cases of lone kings. It does not detect dead positions like impasse by pawn blockade.
`ChessPlayer::forfeit` calls a new virtual method `Board::winPossible(Side)` to check whether the opponent has any pieces beside their King. If not, then the game is drawn.
Resolves #710
=> Adjudicate draw in case of a timeout if the opponent has no means to win

projects/lib/src/board/westernboard.cpp, projects/lib/tests/chessboard/tst_board.cpp
Forbid castling when in check.
Allow castling if a rook attack is intercepted by another attacking
piece with different movement when castling target equals source.
Resolves #616
Resolves #637
Resolves #755
Resolves #756
A test whether the King is in check is added to `WesternBoard::vIsLegalMove` in order to forbid castling moves.
The special code in `WesternBoard::isLegalPosition` for the case of identical castling source and target (occurs in chess960) was removed.
Corrected test case for Grid Chess where a check by Pawn did not prevent castling. Added two of the three examples in issue 616 as test cases for FRC. Added a simple test case for Grid Chess.
**Help needed**: This patch needs intensive testing in chess960 and also in standard chess in order to avoid regression.
**Update**: …
=> Fix castling

.github/workflows/build.yml
The latest versions of MacOS do not support building with Qt 5 so skip it.
=> skip Qt 5 build on macos-latest

.github/workflows/codeql.yml, .lgtm/cpp-queries/qlpack.yml
These local queries were developed some years ago but were disabled when the LGTM service (predecessor to CodeQL) was deprecated.
Reference the directory where the local queries are located with the `queries` parameter in the `codeql/init` step. Add a QL pack configuration so that CodeQL understand this directory contains the queries.
=> re-enable local CodeQL queries

.github/workflows/codeql.yml
The v2 based actions will be deprecated at the end of 2024: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> bump CodeQL Action to v3

projects/lib/src/sprt.cpp
The conditions which must be met for $H_0$ or $H_1$ to be accepted have been updated to use closed intervals $\left]-\infty, B\right]$ and $\left[A, \infty\right[$ respectively, matching the theory found in the original paper by [Abraham Wald](https://doi.org/10.1214%2Faoms%2F1177731118).
=> chore: update sprt completion conditions to match theory

projects/lib/src/board/westernboard.cpp
In the position "8/1k5p/4P3/1q3b2/6PP/7K/5QR1/1q1q4 b - - 0 53" the move b5d3 is Q5d3+ not Qb5d3+.
=> Fix error in standard algebraic notation disambiguity logic
